"""
Data Source Management Module
Provides documentation on the data sources used in each module.
"""

import tkinter as tk
from tkinter import ttk

from common import (
    COLORS, configure_styles, center_window, create_styled_button
)
from data_manager import (
    SOURCE_DIR, TYPE_MAPPING_DIR, MAPPING_DIR, LOGS_DIR,
    PF_RELAY_MODELS_DIR, PF_FUSE_MODELS_DIR,
    PF_DEVICE_VALIDATION_DIR, MAPPING_VALIDATION_DIR, FUSE_DATASHEET_DIR
)


class DataSourcesWindow:
    """Window for Data Source Management documentation."""

    def __init__(self, parent):
        """Initialize the Data Sources window."""
        self.parent = parent
        self.window = tk.Toplevel(parent)
        self.window.title("Data Source Management")
        self.window.geometry("900x800")
        self.window.minsize(800, 650)
        self.window.configure(bg=COLORS['bg_primary'])

        # Make window modal
        self.window.transient(parent)
        self.window.grab_set()

        # Center window
        center_window(self.window, 900, 800)

        # Configure styles
        configure_styles()

        # Build UI
        self._create_widgets()

        # Handle window close
        self.window.protocol("WM_DELETE_WINDOW", self._on_return)

    def _create_widgets(self):
        """Create all GUI widgets."""
        # Main container
        main_frame = ttk.Frame(self.window, style="Main.TFrame")
        main_frame.pack(fill=tk.BOTH, expand=True, padx=20, pady=20)

        # Header section
        self._create_header(main_frame)

        # Content section (scrollable)
        self._create_content(main_frame)

        # Footer section with buttons
        self._create_footer(main_frame)

    def _create_header(self, parent):
        """Create the header section."""
        header_frame = tk.Frame(parent, bg=COLORS['bg_primary'])
        header_frame.pack(fill=tk.X, pady=(0, 15))

        # Title
        title_label = tk.Label(
            header_frame,
            text="Data Source Management",
            font=('Segoe UI', 24, 'bold'),
            fg=COLORS['accent'],
            bg=COLORS['bg_primary']
        )
        title_label.pack(anchor='w')

        # Introduction text
        intro_text = (
            "This section outlines the source data used in each module for this application."
        )
        intro_label = tk.Label(
            header_frame,
            text=intro_text,
            font=('Segoe UI', 11),
            fg=COLORS['text_secondary'],
            bg=COLORS['bg_primary'],
            wraplength=850,
            justify=tk.LEFT
        )
        intro_label.pack(anchor='w', pady=(10, 0))

    def _create_content(self, parent):
        """Create the main content section with scrollbar."""
        # Card-like container
        content_container = ttk.Frame(parent, style="Card.TFrame")
        content_container.pack(fill=tk.BOTH, expand=True)

        # Add subtle border effect
        border_frame = tk.Frame(
            content_container,
            bg=COLORS['border'],
            highlightthickness=0
        )
        border_frame.pack(fill=tk.BOTH, expand=True, padx=1, pady=1)

        # Canvas for scrolling
        canvas = tk.Canvas(border_frame, bg=COLORS['bg_secondary'], highlightthickness=0)
        scrollbar = ttk.Scrollbar(border_frame, orient=tk.VERTICAL, command=canvas.yview)

        scrollable_frame = tk.Frame(canvas, bg=COLORS['bg_secondary'])

        scrollable_frame.bind(
            "<Configure>",
            lambda e: canvas.configure(scrollregion=canvas.bbox("all"))
        )

        canvas.create_window((0, 0), window=scrollable_frame, anchor="nw")
        canvas.configure(yscrollcommand=scrollbar.set)

        # Bind mousewheel
        canvas.bind_all("<MouseWheel>", lambda e: canvas.yview_scroll(int(-1 * (e.delta / 120)), "units"))

        scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
        canvas.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)

        # Store canvas reference for cleanup
        self.content_canvas = canvas

        # Add content to scrollable frame
        self._add_data_source_content(scrollable_frame)

    def _add_data_source_content(self, parent):
        """Add the data source documentation content."""
        content_frame = tk.Frame(parent, bg=COLORS['bg_secondary'], padx=20, pady=20)
        content_frame.pack(fill=tk.BOTH, expand=True)

        # Section 1: IPS Relay Patterns
        self._add_section(
            content_frame,
            "1. IPS Relay Patterns",
            [
                "The IPS Relay Patterns table is built from the following data sources:",
                "Report-Cache-ProtectionSettingIDs-EE.csv",
                "Report-Cache-ProtectionSettingIDs-EX.csv",
                "",
                "These files are located at the following network location:",
                str(SOURCE_DIR),
                "",
                "These files are currently generated by NetDash queries and may be refreshed by running the ips_to_pf.py python script in PowerFactory."
            ],
            is_first=True
        )

        # Section 2: PowerFactory Relay Models
        self._add_section(
            content_frame,
            "2. PowerFactory Relay Models",
            [
                "The PowerFactory Relay Models table is built from the following data source:",
                "pf_relay_models.csv",
                "",
                "This file is located at the following location:",
                str(PF_RELAY_MODELS_DIR),
                "",
                "This file is generated by running the pf_relay_models.py python script in PowerFactory.",
                "",
                'The "Model Validated" column of this table is built from the following data source:',
                "PowerFactory device validation log.csv",
                "",
                "This file is found at the following location:",
                str(PF_DEVICE_VALIDATION_DIR),
                "",
                "This file is user maintained."
            ]
        )

        # Section 3: PowerFactory Fuse Models
        self._add_section(
            content_frame,
            "3. PowerFactory Fuse Models",
            [
                "The PowerFactory Fuse Models table is built from the following data source:",
                "pf_fuse_models.csv",
                "",
                "This file is located at the following location:",
                str(PF_FUSE_MODELS_DIR),
                "",
                "This file is generated by running the pf_fuse_models.py python script in PowerFactory.",
                "",
                'The "Fuse Datasheet" column of this table is built from the following data source:',
                "Fuse datasheet log.csv",
                "",
                "This file is found at the following location:",
                str(FUSE_DATASHEET_DIR),
                "",
                "This file is user maintained."
            ]
        )

        # Section 4: IPS to PowerFactory Mapping Files
        self._add_section(
            content_frame,
            "4. IPS to PowerFactory Mapping Files",
            [
                "The IPS to PowerFactory Mapping Files table is built from the following data sources:",
                "type_mapping.csv",
                "mapping folder",
                "",
                "These files are located at the following network locations:",
                f"type_mapping.csv: {TYPE_MAPPING_DIR}",
                f"mapping folder: {MAPPING_DIR}",
                "",
                "These files are user maintained.",
                "",
                'The "Mapping File Validated" column of this table is built from the following data source:',
                "IPS to PF mapping file validation log.csv",
                "",
                "This file is found at the following location:",
                str(MAPPING_VALIDATION_DIR),
                "",
                "This file is user maintained."
            ]
        )

        # Section 5: IPS to PowerFactory Script Maintenance
        self._add_section(
            content_frame,
            "5. IPS to PowerFactory Script Maintenance",
            [
                "The IPS to PowerFactory Script Maintenance table is built from the following data source:",
                "ips_to_pf.log",
                "",
                "This file is located at the following network location:",
                str(LOGS_DIR),
                "",
                "This file is generated by running the pf_relay_models.py python script in PowerFactory."
            ]
        )

    def _add_section(self, parent, title, content_lines, is_first=False):
        """Add a section with title and content lines."""
        # Section title
        title_label = tk.Label(
            parent,
            text=title,
            font=('Segoe UI', 14, 'bold'),
            fg=COLORS['accent'],
            bg=COLORS['bg_secondary']
        )
        title_label.pack(anchor='w', pady=(0 if is_first else 20, 10))

        # Content lines
        for line in content_lines:
            if line == "":
                # Empty line for spacing
                spacer = tk.Frame(parent, bg=COLORS['bg_secondary'], height=5)
                spacer.pack(anchor='w')
            else:
                content_label = tk.Label(
                    parent,
                    text=line,
                    font=('Segoe UI', 11),
                    fg=COLORS['text_secondary'],
                    bg=COLORS['bg_secondary'],
                    anchor='w',
                    justify=tk.LEFT
                )
                content_label.pack(anchor='w', padx=(20, 0))

    def _create_footer(self, parent):
        """Create the footer section with buttons."""
        footer_frame = tk.Frame(parent, bg=COLORS['bg_primary'])
        footer_frame.pack(fill=tk.X, pady=(15, 0))

        # Button container (right side)
        button_container = tk.Frame(footer_frame, bg=COLORS['bg_primary'])
        button_container.pack(side=tk.RIGHT)

        # Exit button
        create_styled_button(
            button_container,
            "Exit Application",
            self._on_exit,
            COLORS['exit_btn'],
            COLORS['exit_btn_hover']
        )

        # Return button
        create_styled_button(
            button_container,
            "Return",
            self._on_return,
            COLORS['return_btn'],
            COLORS['return_btn_hover']
        )

    def _on_return(self):
        """Handle return button click."""
        self.content_canvas.unbind_all("<MouseWheel>")
        self.window.grab_release()
        self.window.destroy()

    def _on_exit(self):
        """Handle exit button click."""
        self.window.destroy()
        self.parent.quit()
        self.parent.destroy()