# PowerFactory Protection Device Management - Maintenance Guide

## Overview

The PowerFactory Protection Device Management application is a Python GUI tool for managing electrical protection device data. It serves as a centralized interface for handling data flows between IPS (protection device patterns) and PowerFactory (electrical modeling software), with a focus on relay and fuse device management.

---

## Application Modules

The application consists of the following modules accessible from the main landing page:

| Module | Description |
|--------|-------------|
| **1. IPS Relay Patterns** | View and analyze protection relay patterns from IPS data |
| **2. PowerFactory Relay Models** | Manage relay models in PowerFactory |
| **3. PowerFactory Fuse Models** | Manage fuse models in PowerFactory |
| **4. IPS to PowerFactory Mapping Files** | Configure mapping between IPS and PowerFactory data |
| **5. IPS to PowerFactory Script Maintenance** | View script run logs and failed transfer details |
| **6. Relay and Mapping Validation Suite** | Guidance on validating relay models and mapping files |
| **Data Source Management** | Documentation of data sources used in each module |

---

## Data Sources

### Directory Structure

Data sources are organized into two categories:

**Project-Relative Data Sources** (stored within the project directory):
- These files move with the project when the repository is relocated
- Located in subdirectories of the project root

**External Data Sources** (absolute paths):
- Located under: `E:\Programming\_python_work\protection-device-management\Data sources\`
- May need updating when moving to a new environment

### 1. IPS Relay Patterns Data

**Location:** `E:\Programming\_python_work\protection-device-management\Data sources\Queries`

| File | Description | Maintenance |
|------|-------------|-------------|
| `Report-Cache-ProtectionSettingIDs-EE.csv` | Regional IPS relay pattern data | Auto-generated by NetDash queries |
| `Report-Cache-ProtectionSettingIDs-EX.csv` | SEQ IPS relay pattern data | Auto-generated by NetDash queries |

**Required Columns:**
- `patternname` - The relay pattern name
- `assetname` - The associated asset name

**Refresh Method:** Run the `ips_to_pf.py` Python script in PowerFactory

---

### 2. PowerFactory Relay Models Data

**Location:** `<project_root>\pf_relay_models` (project-relative)

| File | Description | Maintenance |
|------|-------------|-------------|
| `pf_relay_models.csv` | PowerFactory relay model definitions | Auto-generated by script |

**Required Columns:**
- `Manufacturer` - Relay manufacturer name
- `Model` - Relay model name
- `Used in EQL` - Whether the model is used in EQL

**Refresh Method:** Run the `pf_relay_models.py` Python script in PowerFactory

#### Model Validated Column

**Location:** `<project_root>\pf_device_validation` (project-relative)

| File | Description | Maintenance |
|------|-------------|-------------|
| `PowerFactory device validation log.csv` | List of validated relay models | User maintained |

**Format:** Single column CSV with header. Each row contains a relay model name that has been validated. The model name must exactly match the `Model` column in `pf_relay_models.csv`.

**Example:**
```csv
Model
RED615
SEL-751
ABB REF615
```

---

### 3. PowerFactory Fuse Models Data

**Location:** `<project_root>\pf_fuse_models` (project-relative)

| File | Description | Maintenance |
|------|-------------|-------------|
| `pf_fuse_models.csv` | PowerFactory fuse model definitions | Auto-generated by script |

**Required Columns:**
- `Fuse` - Fuse name
- `Type` - Fuse type
- `EQL Standard` - Whether the fuse is EQL standard

**Refresh Method:** Run the `pf_fuse_models.py` Python script in PowerFactory

#### Fuse Datasheet Column

**Location:** `<project_root>\fuse_datasheets` (project-relative)

| File | Description | Maintenance |
|------|-------------|-------------|
| `Fuse datasheet log.csv` | List of fuses with datasheets | User maintained |

**Format:** Single column CSV with header. Each row contains a fuse name that has an associated datasheet. The fuse name must exactly match the `Fuse` column in `pf_fuse_models.csv`.

**Example:**
```csv
Fuse
HRC_100A
HRC_200A
SMD-50
```

---

### 4. IPS to PowerFactory Mapping Files Data

**Type Mapping Location:** `E:\Programming\_python_work\protection-device-management\Data sources\type mapping`

| File | Description | Maintenance |
|------|-------------|-------------|
| `type_mapping.csv` | Maps IPS patterns to PowerFactory models and mapping files | User maintained |

**Required Columns:**
- `IPS` - IPS pattern name
- `PF_MODEL` - PowerFactory model name
- `MAPPING_FILE` - Name of the mapping file (without .csv extension)

**Mapping Files Location:** `E:\Programming\_python_work\protection-device-management\Data sources\mapping`

All `.csv` files in this directory are treated as mapping files. The filename (without extension) should match entries in the `MAPPING_FILE` column of `type_mapping.csv`.

#### Mapping File Validated Column

**Location:** `<project_root>\ips_to_pf_mapping_file_validation` (project-relative)

| File | Description | Maintenance |
|------|-------------|-------------|
| `IPS to PF mapping file validation log.csv` | List of validated mapping files | User maintained |

**Format:** Single column CSV with header. Each row contains a mapping file name (without .csv extension) that has been validated.

**Example:**
```csv
Mapping File
ABB_REF615
SEL_351
GE_F60
```

---

### 5. Script Maintenance Log Data

**Location:** `E:\Programming\_python_work\protection-device-management\Data sources\logs`

| File | Description | Maintenance |
|------|-------------|-------------|
| `ips_to_pf` | JSON log file of script runs | Auto-generated by script |

**Format:** JSON lines format (one JSON object per line). Each log entry contains:
- `timestamp` - ISO format timestamp
- `message` - Log message, including "Data capture list: [...]" entries

**Refresh Method:** Generated automatically when running the `pf_relay_models.py` Python script in PowerFactory

**Note:** Log contents can be cleared using the "Delete Log File Contents" button in the Script Maintenance module.

---

## Data Source Summary Table

| Data Source | Location | Maintenance Type |
|-------------|----------|------------------|
| IPS Relay Patterns (EE) | `Data sources\Queries\Report-Cache-ProtectionSettingIDs-EE.csv` | Auto-generated |
| IPS Relay Patterns (EX) | `Data sources\Queries\Report-Cache-ProtectionSettingIDs-EX.csv` | Auto-generated |
| PowerFactory Relay Models | `<project_root>\pf_relay_models\pf_relay_models.csv` | Auto-generated |
| PowerFactory Fuse Models | `<project_root>\pf_fuse_models\pf_fuse_models.csv` | Auto-generated |
| Type Mapping | `Data sources\type mapping\type_mapping.csv` | User maintained |
| Mapping Files | `Data sources\mapping\*.csv` | User maintained |
| Script Logs | `Data sources\logs\ips_to_pf` | Auto-generated |
| Device Validation Log | `<project_root>\pf_device_validation\PowerFactory device validation log.csv` | User maintained |
| Mapping Validation Log | `<project_root>\ips_to_pf_mapping_file_validation\IPS to PF mapping file validation log.csv` | User maintained |
| Fuse Datasheet Log | `<project_root>\fuse_datasheets\Fuse datasheet log.csv` | User maintained |

---

## Project Directory Structure

The following data source folders should exist in the project root directory:

```
protection-device-management/
├── main.py                              # Main application entry point
├── common.py                            # Shared utilities and styling
├── data_manager.py                      # Centralized data loading and caching
├── ips_relay_patterns.py                # IPS Relay Patterns module
├── relay_models.py                      # PowerFactory Relay Models module
├── fuse_models.py                       # PowerFactory Fuse Models module
├── mapping_files.py                     # IPS to PowerFactory Mapping Files module
├── script_maintenance.py                # Script Maintenance module
├── validation_suite.py                  # Validation Suite module
├── data_sources.py                      # Data Source Management module
├── placeholder.py                       # Placeholder window for features under construction
├── pf_relay_models/                     # Project-relative data source
│   └── pf_relay_models.csv
├── pf_fuse_models/                      # Project-relative data source
│   └── pf_fuse_models.csv
├── pf_device_validation/                # Project-relative data source
│   └── PowerFactory device validation log.csv
├── ips_to_pf_mapping_file_validation/   # Project-relative data source
│   └── IPS to PF mapping file validation log.csv
├── fuse_datasheets/                     # Project-relative data source
│   └── Fuse datasheet log.csv
└── Data sources/                        # External data sources (absolute path)
    ├── Queries/
    ├── mapping/
    ├── type mapping/
    └── logs/
```

---

## Validation Procedures

### Relay Model Validation

1. Configure the relay in the model with validated settings
2. Execute a short circuit command
3. Check if the relay trips as expected
4. Provide a trace of all input and output signals for each relay block
5. Move all documentation to: `<project_root>\pf_device_validation`
6. Update the PowerFactory device validation log with the exact name of the PowerFactory Relay Model

### Mapping File Validation

*Note: This should only be performed on relay models that have been validated.*

1. Using the `ips_to_pf.py` script and the mapping file, apply known relay settings from a test relay setting ID
2. Verify that all relay attributes match the relay setting ID
3. Move all documentation to: `<project_root>\ips_to_pf_mapping_file_validation`
4. Update the IPS to PF mapping file validation log with the exact name of the mapping file

---

## Modifying Data Source Locations

All data source directory paths are defined as constants in `data_manager.py`:

```python
# Project root directory (automatically determined)
PROJECT_ROOT = Path(__file__).parent

# External data sources (absolute paths - may need updating when moving to new environment)
SOURCE_DIR = Path(r"E:\...\Data sources\Queries")
MAPPING_DIR = Path(r"E:\...\Data sources\mapping")
TYPE_MAPPING_DIR = Path(r"E:\...\Data sources\type mapping")
LOGS_DIR = Path(r"E:\...\Data sources\logs")

# Project-relative data sources (stored within the project directory)
PF_RELAY_MODELS_DIR = PROJECT_ROOT / "pf_relay_models"
PF_FUSE_MODELS_DIR = PROJECT_ROOT / "pf_fuse_models"
PF_DEVICE_VALIDATION_DIR = PROJECT_ROOT / "pf_device_validation"
MAPPING_VALIDATION_DIR = PROJECT_ROOT / "ips_to_pf_mapping_file_validation"
FUSE_DATASHEET_DIR = PROJECT_ROOT / "fuse_datasheets"
```

To change an external data source location:
1. Open `data_manager.py`
2. Modify the appropriate `*_DIR` constant
3. Ensure the new directory exists and contains the required files
4. Restart the application

Project-relative data sources automatically move with the project when the repository is relocated.

---

## Troubleshooting

### Data Not Loading

1. Verify the data source files exist in the expected locations
2. Check that CSV files have the required column headers
3. Ensure files are saved with UTF-8 encoding
4. Check the console output for error messages during startup

### Validation Status Not Updating

1. Ensure the validation log CSV has a header row
2. Verify the entry in the validation log exactly matches the target value (case-sensitive)
3. Restart the application to reload data

### Application Not Starting

1. Ensure all required Python packages are installed:
   - `tkinter` (usually included with Python)
   - `pandas`
2. Check that all module files are present in the application directory
3. Run from command line to see error messages: `python main.py`

### Refreshing Data

The application loads all data at startup. To refresh data:
1. Close the application
2. Update the source files as needed
3. Restart the application

Alternatively, use the `refresh_data()` method on the DataManager instance for programmatic refresh.

---

## Dependencies

- Python 3.x
- pandas
- tkinter (standard library)

---

## Version History

| Version | Date | Changes |
|---------|------|---------|
| 1.0 | Initial | Initial release with all core modules |
| 1.1 | Current | Updated data source locations to use project-relative paths |

---

## Contact

For questions or issues regarding this application, please contact dan.park@energyq.com.au