# PowerFactory Protection Device Management - Maintenance Guide

## Overview

The PowerFactory Protection Device Management application is a Python GUI tool for managing electrical protection device data. It serves as a centralized interface for handling data flows between IPS (protection device patterns) and PowerFactory (electrical modeling software), with a focus on relay and fuse device management.

---

## Application Modules

The application consists of the following modules accessible from the main landing page:

| Module | Description |
|--------|-------------|
| **1. IPS Relay Patterns** | View and analyze protection relay patterns from IPS data |
| **2. PowerFactory Relay Models** | Manage relay models in PowerFactory |
| **3. PowerFactory Fuse Models** | Manage fuse models in PowerFactory |
| **4. IPS to PowerFactory Mapping Files** | Configure mapping between IPS and PowerFactory data |
| **5. IPS to PowerFactory Script Maintenance** | View script run logs and failed transfer details |
| **6. Relay and Mapping Validation Suite** | Guidance on validating relay models and mapping files |
| **Data Source Management** | Documentation of data sources used in each module |

---

## Data Sources

### Directory Structure

All data sources are located under:
```
E:\Programming\_python_work\protection-device-management\Data sources\
```

### 1. IPS Relay Patterns Data

**Location:** `E:\Programming\_python_work\protection-device-management\Data sources\Queries`

| File | Description | Maintenance |
|------|-------------|-------------|
| `Report-Cache-ProtectionSettingIDs-EE.csv` | Regional IPS relay pattern data | Auto-generated by NetDash queries |
| `Report-Cache-ProtectionSettingIDs-EX.csv` | SEQ IPS relay pattern data | Auto-generated by NetDash queries |

**Required Columns:**
- `patternname` - The relay pattern name
- `assetname` - The associated asset name

**Refresh Method:** Run the `ips_to_pf.py` Python script in PowerFactory

---

### 2. PowerFactory Relay Models Data

**Location:** `E:\Programming\_python_work\protection-device-management\Data sources\PowerFactory types`

| File | Description | Maintenance |
|------|-------------|-------------|
| `pf_relay_models.csv` | PowerFactory relay model definitions | Auto-generated by script |

**Required Columns:**
- `Manufacturer` - Relay manufacturer name
- `Model` - Relay model name
- `Used in EQL` - Whether the model is used in EQL

**Refresh Method:** Run the `pf_relay_models.py` Python script in PowerFactory

#### Model Validated Column

**Location:** `E:\Programming\_python_work\protection-device-management\Data sources\PowerFactory device validation`

| File | Description | Maintenance |
|------|-------------|-------------|
| `PowerFactory device validation log.csv` | List of validated relay models | User maintained |

**Format:** Single column CSV with header. Each row contains a relay model name that has been validated. The model name must exactly match the `Model` column in `pf_relay_models.csv`.

**Example:**
```csv
Model
RED615
SEL-751
ABB REF615
```

---

### 3. PowerFactory Fuse Models Data

**Location:** `E:\Programming\_python_work\protection-device-management\Data sources\PowerFactory types`

| File | Description | Maintenance |
|------|-------------|-------------|
| `pf_fuse_models.csv` | PowerFactory fuse model definitions | Auto-generated by script |

**Required Columns:**
- `Fuse` - Fuse name
- `Type` - Fuse type
- `EQL Standard` - Whether the fuse is EQL standard

**Refresh Method:** Run the `pf_fuse_models.py` Python script in PowerFactory

#### Fuse Datasheet Column

**Location:** `E:\Programming\_python_work\protection-device-management\Data sources\Fuse datasheets`

| File | Description | Maintenance |
|------|-------------|-------------|
| `Fuse datasheet log.csv` | List of fuses with datasheets | User maintained |

**Format:** Single column CSV with header. Each row contains a fuse name that has an associated datasheet. The fuse name must exactly match the `Fuse` column in `pf_fuse_models.csv`.

**Example:**
```csv
Fuse
HRC_100A
HRC_200A
SMD-50
```

---

### 4. IPS to PowerFactory Mapping Files Data

**Type Mapping Location:** `E:\Programming\_python_work\protection-device-management\Data sources\type mapping`

| File | Description | Maintenance |
|------|-------------|-------------|
| `type_mapping.csv` | Maps IPS patterns to PowerFactory models and mapping files | User maintained |

**Required Columns:**
- `IPS` - IPS pattern name
- `PF_MODEL` - PowerFactory model name
- `MAPPING_FILE` - Name of the mapping file (without .csv extension)

**Mapping Files Location:** `E:\Programming\_python_work\protection-device-management\Data sources\mapping`

All `.csv` files in this directory are treated as mapping files. The filename (without extension) should match entries in the `MAPPING_FILE` column of `type_mapping.csv`.

#### Mapping File Validated Column

**Location:** `E:\Programming\_python_work\protection-device-management\Data sources\IPS to PF mapping validation`

| File | Description | Maintenance |
|------|-------------|-------------|
| `IPS to PF mapping file validation log.csv` | List of validated mapping files | User maintained |

**Format:** Single column CSV with header. Each row contains a mapping file name (without .csv extension) that has been validated.

**Example:**
```csv
Mapping File
ABB_REF615
SEL_351
GE_F60
```

---

### 5. Script Maintenance Log Data

**Location:** `E:\Programming\_python_work\protection-device-management\Data sources\logs`

| File | Description | Maintenance |
|------|-------------|-------------|
| `ips_to_pf` | JSON log file of script runs | Auto-generated by script |

**Format:** JSON lines format (one JSON object per line). Each log entry contains:
- `timestamp` - ISO format timestamp
- `message` - Log message, including "Data capture list: [...]" entries

**Refresh Method:** Generated automatically when running the `pf_relay_models.py` Python script in PowerFactory

**Note:** Log contents can be cleared using the "Delete Log File Contents" button in the Script Maintenance module.

---

## Data Source Summary Table

| Data Source | Location | Maintenance Type |
|-------------|----------|------------------|
| IPS Relay Patterns (EE) | `Data sources\Queries\Report-Cache-ProtectionSettingIDs-EE.csv` | Auto-generated |
| IPS Relay Patterns (EX) | `Data sources\Queries\Report-Cache-ProtectionSettingIDs-EX.csv` | Auto-generated |
| PowerFactory Relay Models | `Data sources\PowerFactory types\pf_relay_models.csv` | Auto-generated |
| PowerFactory Fuse Models | `Data sources\PowerFactory types\pf_fuse_models.csv` | Auto-generated |
| Type Mapping | `Data sources\type mapping\type_mapping.csv` | User maintained |
| Mapping Files | `Data sources\mapping\*.csv` | User maintained |
| Script Logs | `Data sources\logs\ips_to_pf` | Auto-generated |
| Device Validation Log | `Data sources\PowerFactory device validation\PowerFactory device validation log.csv` | User maintained |
| Mapping Validation Log | `Data sources\IPS to PF mapping validation\IPS to PF mapping file validation log.csv` | User maintained |
| Fuse Datasheet Log | `Data sources\Fuse datasheets\Fuse datasheet log.csv` | User maintained |

---

## Validation Procedures

### Relay Model Validation

1. Configure the relay in the model with validated settings
2. Execute a short circuit command
3. Check if the relay trips as expected
4. Provide a trace of all input and output signals for each relay block
5. Move all documentation to: `Data sources\PowerFactory device validation`
6. Update the PowerFactory device validation log with the exact name of the PowerFactory Relay Model

### Mapping File Validation

*Note: This should only be performed on relay models that have been validated.*

1. Using the `ips_to_pf.py` script and the mapping file, apply known relay settings from a test relay setting ID
2. Verify that all relay attributes match the relay setting ID
3. Move all documentation to: `Data sources\IPS to PF mapping validation`
4. Update the IPS to PF mapping file validation log with the exact name of the mapping file

---

## Application File Structure

```
protection-device-management/
├── main.py                 # Main application entry point and landing page
├── common.py               # Shared utilities, colors, and styling
├── data_manager.py         # Centralized data loading and caching
├── ips_relay_patterns.py   # IPS Relay Patterns module
├── relay_models.py         # PowerFactory Relay Models module
├── fuse_models.py          # PowerFactory Fuse Models module
├── mapping_files.py        # IPS to PowerFactory Mapping Files module
├── script_maintenance.py   # Script Maintenance module
├── validation_suite.py     # Validation Suite module
├── data_sources.py         # Data Source Management module
├── placeholder.py          # Placeholder window for features under construction
└── Data sources/           # All data source files (see above)
```

---

## Modifying Data Source Locations

All data source directory paths are defined as constants in `data_manager.py`:

```python
SOURCE_DIR = Path(r"E:\...\Data sources\Queries")
MAPPING_DIR = Path(r"E:\...\Data sources\mapping")
TYPE_MAPPING_DIR = Path(r"E:\...\Data sources\type mapping")
LOGS_DIR = Path(r"E:\...\Data sources\logs")
PF_TYPES_DIR = Path(r"E:\...\Data sources\PowerFactory types")
PF_DEVICE_VALIDATION_DIR = Path(r"E:\...\Data sources\PowerFactory device validation")
MAPPING_VALIDATION_DIR = Path(r"E:\...\Data sources\IPS to PF mapping validation")
FUSE_DATASHEET_DIR = Path(r"E:\...\Data sources\Fuse datasheets")
```

To change a data source location:
1. Open `data_manager.py`
2. Modify the appropriate `*_DIR` constant
3. Ensure the new directory exists and contains the required files
4. Restart the application

---

## Troubleshooting

### Data Not Loading

1. Verify the data source files exist in the expected locations
2. Check that CSV files have the required column headers
3. Ensure files are saved with UTF-8 encoding
4. Check the console output for error messages during startup

### Validation Status Not Updating

1. Ensure the validation log CSV has a header row
2. Verify the entry in the validation log exactly matches the target value (case-sensitive)
3. Restart the application to reload data

### Application Not Starting

1. Ensure all required Python packages are installed:
   - `tkinter` (usually included with Python)
   - `pandas`
2. Check that all module files are present in the application directory
3. Run from command line to see error messages: `python main.py`

### Refreshing Data

The application loads all data at startup. To refresh data:
1. Close the application
2. Update the source files as needed
3. Restart the application

Alternatively, use the `refresh_data()` method on the DataManager instance for programmatic refresh.

---

## Dependencies

- Python 3.x
- pandas
- tkinter (standard library)

---

## Version History

| Version | Date | Changes |
|---------|------|---------|
| 1.0 | Initial | Initial release with all core modules |

---

## Contact

For questions or issues regarding this application, please contact dan.park@energyq.com.au